export type Locale = "ko" | "ja" | "en";
export type CommunityTab = "all" | "review" | "mate" | "qna";
export type Region = "gobi" | "central" | "north";
export type Theme = "desert" | "family" | "premium";
export type DurationType = "short" | "long";

export type Tour = {
    id: number;
    region: Region;
    theme: Theme;
    durationType: DurationType;
    price: number;
    deposit: number;
    gradient: string;
    heroImage: string;
    title: Record<Locale, string>;
    desc: Record<Locale, string>;
    tags: Record<Locale, string[]>;
    duration: Record<Locale, string>;
    highlights: Record<Locale, string[]>;
};

export type CommunityItem = {
    type: Exclude<CommunityTab, "all">;
    author: string;
    text: string;
};

export type HeroSlide = {
    eyebrow: string;
    title: string;
    desc: string;
    image: string;
};

export const copy = {
    ko: {
        brand: "BlueWolf",
        navTours: "투어상품",
        navBooking: "예약",
        navCommunity: "커뮤니티",
        navFaq: "FAQ",
        login: "로그인",
        heroBadge: "몽골 여행, 더 쉽고 더 세련되게",
        heroTitle: "BlueWolf와 함께\n몽골 여행을 가장 편하게 예약하세요",
        heroDesc:
            "실제 운영을 고려한 몽골 여행 플랫폼. 상품 탐색, 예약, 결제, 후기, 동행 구하기까지 한 번에 연결되는 구조입니다.",
        heroPrimary: "여행 상품 보기",
        heroSecondary: "예약 상담 시작",
        searchPlaceholder: "상품명 또는 키워드 검색",
        allDuration: "전체 일정",
        shortDuration: "3~4일",
        longDuration: "5일 이상",
        allRegion: "전체 지역",
        gobi: "고비",
        central: "중부",
        north: "북부",
        allTheme: "전체 테마",
        desert: "사막",
        family: "가족",
        premium: "프리미엄",
        popularSort: "인기순",
        lowSort: "낮은 가격순",
        highSort: "높은 가격순",
        featured: "추천 여행 상품",
        featuredDesc: "실제 판매용을 염두에 둔 검색/필터/상세 흐름입니다.",
        reset: "필터 초기화",
        details: "상세보기",
        reserve: "예약하기",
        bookingTitle: "예약 상담/신청",
        bookingDesc: "출발 희망일과 인원 정보를 입력하면 예상 금액이 자동 계산됩니다.",
        selectTour: "상품 선택",
        departDate: "출발 희망일",
        guests: "인원 수",
        name: "예약자 이름",
        phone: "연락처",
        memo: "요청사항",
        payDeposit: "예약금 결제 진행",
        getQuote: "견적서 받기",
        communityTitle: "동행 · 후기 커뮤니티",
        faqTitle: "자주 묻는 질문",
        footer: "몽골 전문 여행 플랫폼 · 한국어 / 일본어 / 영어 지원",
        dashboard1: "이번 달 방문자",
        dashboard2: "예약 전환율",
        dashboard3: "평균 객단가",
        dashboard4: "리뷰 평점",
        priceLabel: "1인 기준",
        selectedTour: "선택 상품",
        totalPrice: "예상 총액",
        deposit: "예약금",
        guestsLabel: "인원 수",
        noResults: "검색 결과가 없습니다.",
        noResultsDesc: "다른 조건으로 다시 검색해보세요.",
        tabAll: "전체",
        tabReview: "후기",
        tabMate: "동행",
        tabQna: "질문",
        payReady: "아직 결제가 진행되지 않았습니다.",
        payDone: "예약금 결제가 완료되었습니다. 운영자 확인 후 안내가 발송됩니다.",
        featuredLabel: "이벤트",
        pausedLabel: "일시정지",
        delete: "삭제",
        today: "오늘",
        weekdays: ["일", "월", "화", "수", "목", "금", "토"] as const,
        datePlaceholder: "연도-월-일",
        publishPhase1: "1단계 · MVP 공개",
        publishPhase2: "2단계 · 운영 기능 연결",
        publishPhase3: "3단계 · 실서비스 확장",
        publishDesc1: "정적 랜딩, 상품 탐색, 예약 접수 중심으로 빠르게 오픈",
        publishDesc2: "결제, 관리자, 문의 흐름을 연결해 실제 운영 전환",
        publishDesc3: "커뮤니티, 후기, 다국어 SEO, 분석 고도화 적용",
    },
    ja: {
        brand: "BlueWolf",
        navTours: "ツアー商品",
        navBooking: "予約",
        navCommunity: "コミュニティ",
        navFaq: "FAQ",
        login: "ログイン",
        heroBadge: "モンゴル旅行をもっと簡単に、もっと洗練して",
        heroTitle: "BlueWolfでモンゴル旅行をもっと手軽に予約",
        heroDesc:
            "実運用を意識したモンゴル旅行プラットフォーム。商品検索、予約、決済、レビュー、同行募集まで一つの流れでつながります。",
        heroPrimary: "商品を見る",
        heroSecondary: "予約相談を始める",
        searchPlaceholder: "商品名またはキーワード検索",
        allDuration: "全日程",
        shortDuration: "3〜4日",
        longDuration: "5日以上",
        allRegion: "全地域",
        gobi: "ゴビ",
        central: "中央",
        north: "北部",
        allTheme: "全テーマ",
        desert: "砂漠",
        family: "家族",
        premium: "プレミアム",
        popularSort: "人気順",
        lowSort: "低価格順",
        highSort: "高価格順",
        featured: "おすすめツアー",
        featuredDesc: "実販売を想定した検索/フィルター/詳細導線です。",
        reset: "フィルター初期化",
        details: "詳細を見る",
        reserve: "予約する",
        bookingTitle: "予約相談/申込",
        bookingDesc: "出発希望日と人数を入力すると概算金額が自動計算されます。",
        selectTour: "商品選択",
        departDate: "出発希望日",
        guests: "人数",
        name: "予約者名",
        phone: "連絡先",
        memo: "リクエスト",
        payDeposit: "予約金を支払う",
        getQuote: "見積書を受け取る",
        communityTitle: "同行・レビューコミュニティ",
        faqTitle: "よくある質問",
        footer: "モンゴル専門旅行プラットフォーム · 韓国語 / 日本語 / 英語対応",
        dashboard1: "今月の訪問者",
        dashboard2: "予約転換率",
        dashboard3: "平均客単価",
        dashboard4: "レビュー評価",
        priceLabel: "1名料金",
        selectedTour: "選択商品",
        totalPrice: "概算総額",
        deposit: "予約金",
        guestsLabel: "人数",
        noResults: "検索結果がありません。",
        noResultsDesc: "条件を変えて再検索してください。",
        tabAll: "すべて",
        tabReview: "レビュー",
        tabMate: "同行",
        tabQna: "質問",
        payReady: "まだ決済は開始されていません。",
        payDone: "予約金の支払いが完了しました。確認後に案内が送信されます。",
        featuredLabel: "イベント",
        pausedLabel: "一時停止",
        delete: "削除",
        today: "今日",
        weekdays: ["日", "月", "火", "水", "木", "金", "土"] as const,
        datePlaceholder: "年-月-日",
        publishPhase1: "第1段階 · MVP公開",
        publishPhase2: "第2段階 · 運用機能接続",
        publishPhase3: "第3段階 · 本番拡張",
        publishDesc1: "静的ランディングと商品閲覧、予約受付中心で素早く公開",
        publishDesc2: "決済、管理、問い合わせ導線をつなぎ実運用に移行",
        publishDesc3: "コミュニティ、レビュー、多言語SEO、分析を高度化",
    },
    en: {
        brand: "BlueWolf",
        navTours: "Tours",
        navBooking: "Booking",
        navCommunity: "Community",
        navFaq: "FAQ",
        login: "Log in",
        heroBadge: "Mongolia travel, simpler and smarter",
        heroTitle: "Book your Mongolia trip with BlueWolf the easy way",
        heroDesc:
            "An operations-ready Mongolia travel platform connecting product discovery, booking, payment, reviews, and traveler community in one flow.",
        heroPrimary: "View tours",
        heroSecondary: "Start booking",
        searchPlaceholder: "Search by tour name or keyword",
        allDuration: "All durations",
        shortDuration: "3–4 days",
        longDuration: "5+ days",
        allRegion: "All regions",
        gobi: "Gobi",
        central: "Central",
        north: "North",
        allTheme: "All themes",
        desert: "Desert",
        family: "Family",
        premium: "Premium",
        popularSort: "Most popular",
        lowSort: "Price: low to high",
        highSort: "Price: high to low",
        featured: "Featured tours",
        featuredDesc: "Search, filter, and detail flows designed for real conversion.",
        reset: "Reset filters",
        details: "View details",
        reserve: "Book now",
        bookingTitle: "Booking inquiry / application",
        bookingDesc: "Enter your preferred departure date and guest count to calculate the estimate automatically.",
        selectTour: "Select tour",
        departDate: "Preferred date",
        guests: "Guests",
        name: "Lead traveler",
        phone: "Phone number",
        memo: "Request details",
        payDeposit: "Pay deposit",
        getQuote: "Get quote",
        communityTitle: "Traveler community",
        faqTitle: "Frequently asked questions",
        footer: "Mongolia travel platform · Korean / Japanese / English",
        dashboard1: "Monthly visitors",
        dashboard2: "Booking conversion",
        dashboard3: "Average order value",
        dashboard4: "Review score",
        priceLabel: "Per person",
        selectedTour: "Selected tour",
        totalPrice: "Estimated total",
        deposit: "Deposit",
        guestsLabel: "Guests",
        noResults: "No tours matched your filters.",
        noResultsDesc: "Try adjusting your search or filters.",
        tabAll: "All",
        tabReview: "Reviews",
        tabMate: "Companions",
        tabQna: "Questions",
        payReady: "No payment has started yet.",
        payDone: "Deposit payment completed. A confirmation notice will be sent after review.",
        featuredLabel: "Event",
        pausedLabel: "Paused",
        delete: "Clear",
        today: "Today",
        weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const,
        datePlaceholder: "YYYY-MM-DD",
        publishPhase1: "Phase 1 · MVP Launch",
        publishPhase2: "Phase 2 · Ops Integration",
        publishPhase3: "Phase 3 · Scale Up",
        publishDesc1: "Launch quickly with landing, catalog, and booking request flow.",
        publishDesc2: "Connect payment, admin, and inquiry workflow for live operations.",
        publishDesc3: "Expand community, reviews, multilingual SEO, and analytics.",
    },
} as const;

export const tours: Tour[] = [
    {
        id: 1,
        region: "gobi",
        theme: "desert",
        durationType: "long",
        price: 1690000,
        deposit: 300000,
        gradient: "from-blue-600 to-blue-400",
        heroImage: "/images/hero-gobi.jpg",
        title: { ko: "고비 사막 5박 6일", ja: "ゴビ砂漠 5泊6日", en: "Gobi Desert 5N6D" },
        desc: {
            ko: "가장 인기 있는 대표 코스. 사막, 협곡, 별보기, 게르 숙박까지 한 번에 즐깁니다.",
            ja: "砂漠・峡谷・星空観察・ゲル宿泊まで楽しめる人気コースです。",
            en: "Our signature route covering desert, canyon, stargazing, and ger stay.",
        },
        tags: {
            ko: ["베스트", "별보기", "한국어 가이드"],
            ja: ["人気", "星空", "韓国語ガイド"],
            en: ["Best", "Stargazing", "Korean Guide"],
        },
        duration: { ko: "5박 6일", ja: "5泊6日", en: "5 nights 6 days" },
        highlights: {
            ko: ["고비 사막", "별보기", "게르 숙박", "협곡 투어"],
            ja: ["ゴビ砂漠", "星空観察", "ゲル宿泊", "渓谷ツアー"],
            en: ["Gobi Desert", "Stargazing", "Ger Stay", "Canyon Tour"],
        },
    },
    {
        id: 2,
        region: "central",
        theme: "family",
        durationType: "short",
        price: 990000,
        deposit: 200000,
        gradient: "from-sky-900 to-blue-500",
        heroImage: "/images/hero-terelj.jpg",
        title: { ko: "테를지 · 미니사막 3박 4일", ja: "テレルジ・ミニ砂漠 3泊4日", en: "Terelj & Mini Desert 3N4D" },
        desc: {
            ko: "짧은 일정으로 몽골의 자연을 압축 체험할 수 있는 입문형 상품입니다.",
            ja: "短い日程でモンゴルの自然を楽しめる入門向け商品です。",
            en: "A short route ideal for first-time travelers wanting a compact Mongolia experience.",
        },
        tags: {
            ko: ["입문형", "가성비", "가족 추천"],
            ja: ["入門", "コスパ", "家族向け"],
            en: ["Starter", "Value", "Family"],
        },
        duration: { ko: "3박 4일", ja: "3泊4日", en: "3 nights 4 days" },
        highlights: {
            ko: ["테를지 국립공원", "초원 드라이브", "미니사막", "가벼운 일정"],
            ja: ["テレルジ国立公園", "草原ドライブ", "ミニ砂漠", "短期日程"],
            en: ["Terelj Park", "Steppe Drive", "Mini Desert", "Short Route"],
        },
    },
    {
        id: 3,
        region: "north",
        theme: "premium",
        durationType: "long",
        price: 2090000,
        deposit: 400000,
        gradient: "from-violet-700 to-indigo-400",
        heroImage: "/images/hero-khuvsgul.jpg",
        title: { ko: "홉스골 호수 6박 7일", ja: "フブスグル湖 6泊7日", en: "Khuvsgul Lake 6N7D" },
        desc: {
            ko: "북부 몽골의 고요한 호수와 숲 풍경을 중심으로 한 프리미엄 일정입니다.",
            ja: "北モンゴルの静かな湖と森を楽しむプレミアム日程です。",
            en: "A premium itinerary focused on northern Mongolia's lakes and forest landscapes.",
        },
        tags: {
            ko: ["프리미엄", "호수", "자연휴식"],
            ja: ["プレミアム", "湖", "自然"],
            en: ["Premium", "Lake", "Nature"],
        },
        duration: { ko: "6박 7일", ja: "6泊7日", en: "6 nights 7 days" },
        highlights: {
            ko: ["홉스골 호수", "북부 숲", "프리미엄 동선", "자연 휴식"],
            ja: ["フブスグル湖", "北部の森", "プレミアムルート", "自然休息"],
            en: ["Khuvsgul Lake", "Northern Forest", "Premium Route", "Nature Retreat"],
        },
    },
];

export const slides: Record<Locale, HeroSlide[]> = {
    ko: [
        {
            eyebrow: "고비 사막 시그니처",
            title: "별빛 아래에서 만나는\n몽골의 가장 깊은 밤",
            desc: "사막, 협곡, 게르 숙박, 별보기까지 BlueWolf 대표 코스를 감각적인 배너로 소개합니다.",
            image: "/images/hero-gobi.jpg",
        },
        {
            eyebrow: "테를지 & 초원",
            title: "주말처럼 가볍게 떠나는\n몽골 입문 여행",
            desc: "짧은 일정으로도 충분히 만족할 수 있는 자연 중심 코스를 빠르게 탐색해보세요.",
            image: "/images/hero-terelj.jpg",
        },
        {
            eyebrow: "홉스골 프리미엄",
            title: "호수와 숲이 있는 북부 몽골을\n더 여유롭게 경험하세요",
            desc: "밝고 깨끗한 분위기의 카드형 배너로 프리미엄 일정도 자연스럽게 노출할 수 있습니다.",
            image: "/images/hero-khuvsgul.jpg",
        },
    ],
    ja: [
        {
            eyebrow: "ゴビ砂漠シグネチャー",
            title: "星空の下で出会う\nモンゴルの深い夜",
            desc: "砂漠、渓谷、ゲル宿泊、星空観察まで代表コースを明るいバナーで紹介します。",
            image: "/images/hero-gobi.jpg",
        },
        {
            eyebrow: "テレルジ＆草原",
            title: "週末のように軽やかに出発する\nモンゴル入門旅",
            desc: "短い日程でも満足感の高い自然中心コースをすばやく見つけられます。",
            image: "/images/hero-terelj.jpg",
        },
        {
            eyebrow: "フブスグル プレミアム",
            title: "湖と森がある北モンゴルを\nもっとゆったり体験",
            desc: "明るくクリーンなカード型バナーでプレミアム商品も自然に見せられます。",
            image: "/images/hero-khuvsgul.jpg",
        },
    ],
    en: [
        {
            eyebrow: "Gobi Signature",
            title: "Meet Mongolia's deepest night\nunder a sky full of stars",
            desc: "Introduce BlueWolf's core route with a bright, polished banner featuring desert, canyon, ger stay, and stargazing.",
            image: "/images/hero-gobi.jpg",
        },
        {
            eyebrow: "Terelj & Steppe",
            title: "An easy first Mongolia trip\nthat feels light and flexible",
            desc: "Highlight short and approachable itineraries in a cleaner slide layout for quick browsing.",
            image: "/images/hero-terelj.jpg",
        },
        {
            eyebrow: "Khuvsgul Premium",
            title: "Experience northern Mongolia\nwith more space and calm",
            desc: "Use a bright card-style slide to naturally feature premium lake and forest journeys.",
            image: "/images/hero-khuvsgul.jpg",
        },
    ],
};

export const faq = {
    ko: [
        ["항공권도 함께 예약해주나요?", "기본 상품은 항공권 별도이지만 요청 시 별도 상담이 가능합니다."],
        ["1명도 예약 가능한가요?", "일부 상품은 1인 출발이 가능하며 조건에 따라 요금이 달라질 수 있습니다."],
        ["결제 수단은 어떤 것이 있나요?", "카드, 계좌이체, 간편결제 확장 구조로 설계했습니다."],
    ],
    ja: [
        ["航空券も一緒に予約できますか？", "基本商品には航空券は含まれませんが、別途ご案内可能です。"],
        ["1名でも予約できますか？", "一部商品は1名参加可能で、条件により料金が変わります。"],
        ["決済手段は何がありますか？", "カード、銀行振込、簡単決済に拡張できる構造です。"],
    ],
    en: [
        ["Can you also help with flights?", "Flights are usually excluded, but we can assist separately on request."],
        ["Can solo travelers book?", "Some tours support solo departure, depending on route and pricing conditions."],
        ["What payment methods are available?", "The structure supports card, bank transfer, and quick-pay expansion."],
    ],
} as const;

export const community: Record<Locale, CommunityItem[]> = {
    ko: [
        { type: "mate", author: "Mina", text: "7월 고비 사막 투어 가시는 분 있나요? 준비물 추천 부탁드려요!" },
        { type: "qna", author: "BlueWolf", text: "밤에는 추울 수 있어 얇은 패딩과 보조배터리를 꼭 챙겨주세요." },
        { type: "review", author: "Jisu", text: "테를지 3박 4일 다녀왔는데 부모님과 함께 가기에도 정말 좋았어요." },
    ],
    ja: [
        { type: "mate", author: "Mina", text: "7月のゴビ砂漠ツアーに行く方いますか？持ち物のおすすめを知りたいです。" },
        { type: "qna", author: "BlueWolf", text: "夜は冷えるので、薄手のダウンとモバイルバッテリーをおすすめします。" },
        { type: "review", author: "Jisu", text: "テレルジ3泊4日、両親と一緒でもとても快適でした。" },
    ],
    en: [
        { type: "mate", author: "Mina", text: "Anyone joining the July Gobi tour? Would love packing tips!" },
        { type: "qna", author: "BlueWolf", text: "It gets cold at night, so bring a light padded jacket and a power bank." },
        { type: "review", author: "Jisu", text: "I joined the 3N4D Terelj tour and it was also great for traveling with parents." },
    ],
};

export const publishingSteps = {
    ko: [
        { title: "1단계 · MVP 공개", desc: "정적 랜딩, 상품 탐색, 예약 접수 중심으로 빠르게 오픈" },
        { title: "2단계 · 운영 기능 연결", desc: "결제, 관리자, 문의 흐름을 연결해 실제 운영 전환" },
        { title: "3단계 · 실서비스 확장", desc: "커뮤니티, 후기, 다국어 SEO, 분석 고도화 적용" },
    ],
    ja: [
        { title: "第1段階 · MVP公開", desc: "静的ランディングと商品閲覧、予約受付中心で素早く公開" },
        { title: "第2段階 · 運用機能接続", desc: "決済、管理、問い合わせ導線をつなぎ実運用に移行" },
        { title: "第3段階 · 本番拡張", desc: "コミュニティ、レビュー、多言語SEO、分析を高度化" },
    ],
    en: [
        { title: "Phase 1 · MVP Launch", desc: "Launch quickly with landing, catalog, and booking request flow." },
        { title: "Phase 2 · Ops Integration", desc: "Connect payment, admin, and inquiry workflow for live operations." },
        { title: "Phase 3 · Scale Up", desc: "Expand community, reviews, multilingual SEO, and analytics." },
    ],
} as const;